name: 'Docker Publish'

on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  push_to_registry:
    name: Build image
    runs-on: ubuntu-latest
    if: github.repository == 'juliusknorr/nextcloud-docker-dev'
    strategy:
      fail-fast: false
      matrix:
        container:
          - php85
          - php84
          - php83
          - php82
          - php81
          - php80
          - php74
          - php73
          - php72
          - php71
          - push
          - saml
          - nginx
          - elasticsearch
          - keycloak
          - mailhog
          - ldap
          - lookupserver
          - smb
          - codedev
          - code
          - talk-janus
          - noop
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.container }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.container }}-buildx-
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set dockerfile path
        id: dockerfile
        run: |
          NAME="${{ matrix.container }}"
          DOCKERFILE=$([[ -f "docker/$NAME/Dockerfile" ]] && echo "docker/$NAME/Dockerfile" || echo "docker/Dockerfile.$NAME")
          echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_OUTPUT
      - name: Build container image
        uses: docker/build-push-action@v7
        with:
          push: false
          context: docker/
          platforms: linux/amd64,linux/arm64
          file: ${{ steps.dockerfile.outputs.DOCKERFILE }}
          tags: |
            ghcr.io/juliusknorr/nextcloud-dev-${{ matrix.container }}:${{ github.sha }}
            ghcr.io/juliusknorr/nextcloud-dev-${{ matrix.container }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Push container image
        uses: docker/build-push-action@v7
        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        with:
          push: true
          context: docker/
          platforms: linux/amd64,linux/arm64
          file: ${{ steps.dockerfile.outputs.DOCKERFILE }}
          tags: |
            ghcr.io/juliusknorr/nextcloud-dev-${{ matrix.container }}:${{ github.event_name == 'release' && 'release' || 'latest' }}
            ghcr.io/juliusknorr/nextcloud-dev-${{ matrix.container }}:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Start containers with docker compose
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        run: |
          ./bootstrap.sh
          PHP_VERSION=$(echo ${{ matrix.container }} | sed -e 's/^php//')
          echo "PHP_VERSION=${PHP_VERSION}" >> .env
          # exit if php version is not numeric or below 80 or above 84 to only test against supported ones in server master
          if ! [[ $PHP_VERSION =~ ^[0-9]+$ ]] || [[ $PHP_VERSION -lt 80 ]] || [[ $PHP_VERSION -gt 84 ]]; then
            exit 0
          fi
          docker compose up -d nextcloud
          # wait for nextcloud to be up
          # wait up to 5 minutes
          for i in {1..300}; do
            if curl -s http://nextcloud.local/index.php/login | grep -q 'Login'; then
              break
            fi
            sleep 1
          done
          curl http://nextcloud.local/status.php
      - uses: actions/setup-node@v6
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        with:
          node-version: latest
      - name: Install dependencies
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        working-directory: tests
        run: npm ci
      - name: Install Playwright Browsers
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        working-directory: tests
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        working-directory: tests
        run: npx playwright test
      - uses: actions/upload-artifact@v7
        if: matrix.container == 'php82' || matrix.container == 'php83' || matrix.container == 'php84'
        with:
          name: playwright-report-${{ matrix.container }}
          path: tests/playwright-report/
          retention-days: 30
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
